### ISSUE TITLE
Chocolatey Display Issue

### ISSUE THREAD

**Issue by wjk** [terrajobst/git-istage#1]
I found your project while browsing the list of packages on Chocolatey.org. However, I noticed that the description [as viewable on Chocolatey.org](https://chocolatey.org/packages/git-istage/0.1.3-alpha) contains a visual glitch. Specifically, it says “For more information, see .” The URL after the word “see” is missing. I tracked this down to [this line in the NuGet project](https://github.com/terrajobst/git-istage/blob/master/src/git-istage-nupkg/git-istage-nupkg.nuproj#L31). Apparently `$(ProjectUrl)` is not being expanded correctly during the build, and is being replaced with an empty string.

I am not very knowledgable about the inner workings of a NuGet project, but by looking over the source code I saw one thing that may cause this problem: The `$(ProjectUrl)` [is defined after where it is used](https://github.com/terrajobst/git-istage/blob/master/src/git-istage-nupkg/git-istage-nupkg.nuproj#L34). Have you tried editing the `.nuproj` file in Notepad and moving the line highlighted above the `<Description>` line?

Failing that, I would suggest replacing this token with the full URL to the GitHub repo, between `<>`, like this: `<https://github.com/terrajobst/git-istage>`. Chocolatey.org interprets Markdown, so this would become a hyperlink to the project page.

**Comment by terrajobst** [comment]
Thanks!
