### ISSUE TITLE
Enable vim movements

### ISSUE THREAD

**Issue by giggio** [terrajobst/git-istage#10]
Enable movement with <kbd>j</kbd> and <kbd>k</kbd> (at minimum) and <kbd>G</kbd> and <kbd>g</kbd>. This is very common for people working on command line, with tools like `git diff`.
Supporting `git diff` movements would be a good baseline.

**Comment by tiesmaster** [comment]
@terrajobst Almost correct:`g`: begin of file / `G`: end of file

You can look these up when you're in the `git diff` viewer (which is [`less`](http://man7.org/linux/man-pages/man1/less.1.html)), by pressing `h` for the builtin help page (similar to feature request #11 😉 ):

![screen shot 2018-10-18 at 21 28 36](https://user-images.githubusercontent.com/460904/47178927-e9cef680-d31c-11e8-9184-5048fb551532.png)
