### ISSUE TITLE
Add help keyboard shortcut

### ISSUE THREAD

**Issue by giggio** [terrajobst/git-istage#11]
Adding a command shortcut for help would be useful, as we wouldn't need to come to Github to check the docs. Maybe use <kbd>?</kbd>, as it is very common.

**Comment by terrajobst** [comment]
Totally. It's on my list, but I haven't gotten to it yet. PR would be appreciated :-)

**Comment by tomaszprasolek** [comment]
I have started doing this on my fork. I should done this by the end of week.

**Comment by giggio** [comment]
Cool, that helped a lot. Thanks!
