### ISSUE TITLE
`git istage` doesn't work after installation while `git-istage` does

### ISSUE THREAD

**Issue by terrajobst** [terrajobst/git-istage#22]
It still does not work on macOSX 10.13.3, I have added the dotnet tools folder to the PATH: 

```bash
#Folders: 
export DOTNET_TOOLS_HOME=$HOME/.dotnet/tools

# Binaries:
export PATH=DOTNET_TOOLS_HOME:$PATH
```

however, when I run `git-istage` in the terminal it works, but when I run `git istage` it says no such a command found!

```bash
git: 'istage' is not a git command. See 'git --help'.

The most similar command is
	stage
```

My git versions is `2.16.2`

Thanks anyway.

_Originally posted by @shahabganji in https://github.com/terrajobst/git-istage/issues/12#issuecomment-431735670_

**Comment by terrajobst** [comment]
Sight. I'm losing track. This is a duplicate of #21.

**Comment by shahabganji** [comment]
@terrajobst just for other devs reaching here in the future, the exports mentioned above missed a `$` for `Binaries` part

```bash
#Folders: 
export DOTNET_TOOLS_HOME=$HOME/.dotnet/tools

# Binaries:
export PATH=$DOTNET_TOOLS_HOME:$PATH
```
