### ISSUE TITLE
Editable key bindings

### ISSUE THREAD

**Issue by n-develop** [terrajobst/git-istage#27]
It would be cool, if the key bindings are editable / configurable somehow.
I use the neo-layout (https://neo-layout.org/) for my keyboard and the `GoToNextHunk` and `GoToPreviousHunk` just don't work for me, as it uses a different key code for `[` and `]`. 
But even if I switch to my "normal" keyboard layout, which is german, I cannot use it, because it's also represented by other codes.

If configurable key bindings are no option, maybe both commands can be mapped to other keys, which will work on all (or most) layouts? That would be cool, because `GoToNextHunk` and `GoToPreviousHunk` are really useful commands.

**Comment by terrajobst** [comment]
Fixed by #29
