### ISSUE TITLE
weird behavior git-istage on staging 

### ISSUE THREAD

**Issue by alirezanet** [terrajobst/git-istage#41]
I'm not sure why, but git-istage can not stage anything in my system.
I get this after pressing S or Alt+S.
![image](https://user-images.githubusercontent.com/7004080/127726814-28ef37bc-c268-43c4-b694-1fdd08871b0d.png)
how can I debug or get some error logs at least?
git-istage      0.3.33

**Comment by alirezanet** [comment]
also, this git-istage can not detect changes correctly.

right side is git diff and left side is git-istage.
![image](https://user-images.githubusercontent.com/7004080/129251806-9b4df12d-d9be-4de7-ae97-5fda93dd70ff.png)

**Comment by jmelosegui** [comment]
@alirezanet I was having the same issue with a particular file, where istage was seeing the whole file as changed.
I realized that I had some inconsistencies in the way the line endings were treated (`CRLF` vs `LF`) in my repository.
So I renormalized the repo using the following steps.

1. Be sure you don't have any changes pending for commit and your working tree and the staging areas are all clean.
2. add a `.gitattributes` to your project with the content `* text=auto`
```shell
echo "* text=auto" > .gitattributes
```
3. run `git add --renormalize .`
4. run `git commit -m "Introduce end-of-line normalization"`

After this  `git-istage` shows the differences as expected.

Let me know if that helps.

Thanks @terrajobst, for this awesome tool

**Comment by alirezanet** [comment]
Hi, @jmelosegui. Thank you for your reply.
I've tried this solution, didn't work for me, I don't know what is wrong really.

**Comment by alirezanet** [comment]
@jmelosegui you were right. 
I fixed the problem kind of by disabling the below configs
```
git config --local core.autocrlf false
git config --local core.safecrlf false
```
git istage isn't compatible with these two configurations I guess.

**Comment by alirezanet** [comment]
I did a little bit of debugging, looks like the generated patch file is correct but git can not apply the patch! 

example generated patch file by git istage:
```git
--- a/Server/src/Presentation/appsettings.json
+++ b/Server/src/Presentation/appsettings.json
@@ -5,7 +5,7 @@
          "System": "Information",
          "Microsoft": "Information",
          "Hangfire": "Warning",
-         "HealthChecks.*": "Error",
+         "HealthChecks.*": "Information",
          "System.Net.Http.HttpClient.health-checks": "Error"
       }
    },
```
git output after applying this patch:
```git
error: patch failed: Server/src/Presentation/appsettings.json:5
error: Server/src/Presentation/appsettings.json: patch does not apply
--- a/Server/src/Presentation/appsettings.json
+++ b/Server/src/Presentation/appsettings.json
@@ -5,7 +5,7 @@
          "System": "Information",
          "Microsoft": "Information",
          "Hangfire": "Warning",
-         "HealthChecks.*": "Error",
+         "HealthChecks.*": "Information",
          "System.Net.Http.HttpClient.health-checks": "Error"
       }
    },

```
any idea why this is happening?
