### ISSUE TITLE
question - CI build 

### ISSUE THREAD

**Issue by alirezanet** [terrajobst/git-istage#44]
Hi,
In the readme, you've added this line 

```cmd
dotnet tool install git-istage -g --add-source https://nuget.pkg.github.com/terrajobst/index.json
```
after running this command I get a ` Response status code does not indicate success: 401 (Unauthorized). ` error. 

honestly, I'm not sure what this command does exactly but I assumed that I can install a newer package using this. (trying to install `v0.3.53` that does not exist in NuGet yet)

**how can I use this?**

**Comment by alirezanet** [comment]
Sorry my bad, I should have installed the package from the local source!
```
dotnet tool install git-istage -g --add-source PATH-TO-BIN-FOLDER
```

**Comment by terrajobst** [comment]
Odd. I kinda assumed that the CI feed would be public. That's interesting!

I just released a new version. In a few minutes, you should be able to run

```
dotnet tool update git-istage -g
```
