### ISSUE TITLE
How does this improve on `git add -p`?

### ISSUE THREAD

**Issue by blocka** [terrajobst/git-istage#5]
`git add -p` is part of my everyday experience. I use it even if I know exactly what my changes are, and what I want to stage.

How would this improve my experience?

**Comment by terrajobst** [comment]
> How would this improve my experience?

I find `git add -p` extremely cumbersome to use. My tool does the following:

1. It presents you with an output identical to `git diff`
2. You can navigate files by using left and right arrow keys
3. You can navigate hunks using the bracket keys
4. You can stage hunks using <kbd>Shift</kbd> <kbd>S</kbd> and individual lines by <kbd>S</kbd>
5. You can toggle the view for unstaged / staged with <kbd>T</kbd>
6. Hit <kbd>Esc</kbd> when you're done

If you like `git add -p` then maybe this tool doesn't do much for you but I'm personally much faster with `git istage`.

**Comment by terrajobst** [comment]
I've also recorded a quick video, maybe this answers it as well:

[![thumbnail](https://user-images.githubusercontent.com/5169960/46930452-84b49180-cffa-11e8-9b28-38ec1a66a358.png)](https://www.youtube.com/watch?v=2nNJly4uim0)
