### ISSUE TITLE
Install with scoop

### ISSUE THREAD

**Issue by johannesegger** [terrajobst/git-istage#8]
First of all: Thanks for this tool and thanks for your compiler creation series that led me to this.

But I don't quite understand why this tool is distributed as a dotnet tool. It's language agnostic as far as I can tell.

I would love writing a [scoop](https://scoop.sh/) manifest for it, but I'm not quite sure where the version number comes from, i.e. how is the Azure DevOps build id related to the version (e.g. the NuGet one)?

I can see that there is quite a bit of "modernization" going on currently. Maybe there is room for publishing the artifacts as GitHub releases. This would make writing a scoop manifest super simple and having version numbers linked to commits would be useful anyways.

**Comment by slang25** [comment]
I think step 1 would be to build some self contained binaries for each platform, like this:
https://github.com/terrajobst/git-istage/compare/master...slang25:warp-dist?expand=1

Disclaimer: I won't be at a windows laptop until next week so cannot test, the macos part works (although suffers from #9 so isn't much use currently).

Then it's a case of adding the scoop manifest.

**Comment by johannesegger** [comment]
Ok thanks for your info.

Yep, I think @slang25 nailed it. _dotnet tool_ creates the platform-specific exe out of platform neutral dlls. Scoop works only with ready-made x86/x64 exe files.

**Comment by johannesegger** [comment]
...except when you have scoop build the platform-specific exe file using dotnet tool. I mean it might be possible to create a scoop manifest that just runs `dotnet tool install istage --tool-path ...`. I'll explore that soon.

**Comment by johannesegger** [comment]
I [proposed](https://github.com/lukesampson/scoop/pull/2708) to put a scoop manifest for git-istage in the main scoop bucket, let's see what they say.

**Comment by johannesegger** [comment]
Awesome, the manifest for git-istage got merged, see https://github.com/lukesampson/scoop/pull/2708.

As a scoop user you can now install git-istage with: `scoop install git-istage`.

Behind the scenes it still runs `dotnet tool install git-istage`, but it's all managed by scoop which I personally like.
