### ISSUE TITLE
istage not working (under MinTTY)

### ISSUE THREAD

**Issue by tiesmaster** [terrajobst/git-istage#9]
[Like I said](https://www.youtube.com/watch?v=3XM9vUGduhk&lc=UgyyVQ8xT7EBx89iyY94AaABAg), trying out istage straight away on the Monday ;) Though, it crashes on startup, I'm guessing because I'm using the MinTTY shell that Git for Windows allows you to use as alternative to the default Windows console. Crosschecking from plain old `cmd.exe` confirms that.

Do you accept PRs? (Don't know if I have time, but won't start unless it's valuable ;)

Crash message:

````
$ git istage

Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.get_CursorVisible()
   at GitIStage.Application.Run() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 33
   at GitIStage.Program.Main() in /home/vsts/work/1/s/src/git-istage/Program.cs:line 32
````

**Comment by tiesmaster** [comment]
I just installed ConEmu, and it's failing there too, BTW.

**Comment by terrajobst** [comment]
Super weird. I can use it from both cmd.exe as well as ConEmu. Which OS version are you on?





> Do you accept PRs? (Don't know if I have time, but won't start unless it's valuable ;)

ABSOLUTELY! :-)
